SECRET_KEY = 'development secret'

SQLALCHEMY_DATABASE_URI = 'postgresql://localhost/bkr'

SECURITY_CONFIRMABLE = True
SECURITY_REGISTERABLE = True
SECURITY_RECOVERABLE = True
SECURITY_TRACKABLE = True
SECURITY_CHANGEABLE = True

MAIL_SERVER = 'smtp.ym.163.com'
MAIL_PORT = 994
MAIL_USE_SSL = True
SECURITY_EMAIL_SENDER = MAIL_USERNAME = 'noreply@decentfox.com'
MAIL_PASSWORD = ''
