"""unique account.code

Revision ID: 21788c276468
Revises: 6bdb37c0e131
Create Date: 2016-01-06 21:18:41.304209

"""

# revision identifiers, used by Alembic.
revision = '21788c276468'
down_revision = '6bdb37c0e131'
branch_labels = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bkr_accounts', ['code'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bkr_accounts', type_='unique')
    ### end Alembic commands ###
