"""security

Revision ID: ad6d7708b1a0
Revises: 691377c94ec1
Create Date: 2016-01-12 16:58:43.122066

"""

# revision identifiers, used by Alembic.
revision = 'ad6d7708b1a0'
down_revision = '691377c94ec1'
branch_labels = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bkr_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bkr_users_x_roles',
    sa.Column('users_id', sa.BigInteger(), nullable=True),
    sa.Column('roles_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['roles_id'], ['bkr_roles.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['bkr_users.id'], )
    )
    op.add_column('bkr_users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('bkr_users', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('bkr_users', sa.Column('current_login_at', sa.DateTime(), nullable=True))
    op.add_column('bkr_users', sa.Column('current_login_ip', sa.Unicode(), nullable=True))
    op.add_column('bkr_users', sa.Column('email', sa.Unicode(), nullable=True))
    op.add_column('bkr_users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('bkr_users', sa.Column('last_login_ip', sa.Unicode(), nullable=True))
    op.add_column('bkr_users', sa.Column('login_count', sa.BigInteger(), nullable=True))
    op.add_column('bkr_users', sa.Column('password', sa.Unicode(), nullable=True))
    op.create_unique_constraint(None, 'bkr_users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bkr_users', type_='unique')
    op.drop_column('bkr_users', 'password')
    op.drop_column('bkr_users', 'login_count')
    op.drop_column('bkr_users', 'last_login_ip')
    op.drop_column('bkr_users', 'last_login_at')
    op.drop_column('bkr_users', 'email')
    op.drop_column('bkr_users', 'current_login_ip')
    op.drop_column('bkr_users', 'current_login_at')
    op.drop_column('bkr_users', 'confirmed_at')
    op.drop_column('bkr_users', 'active')
    op.drop_table('bkr_users_x_roles')
    op.drop_table('bkr_roles')
    ### end Alembic commands ###
