"""user.name

Revision ID: eb2c21bd0856
Revises: d5229885c9bd
Create Date: 2016-01-16 17:37:01.328009

"""

# revision identifiers, used by Alembic.
revision = 'eb2c21bd0856'
down_revision = 'd5229885c9bd'
branch_labels = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bkr_users', sa.Column('name', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bkr_users', 'name')
    ### end Alembic commands ###
